version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./gateway:/app
    networks:
      - taeheonai-network
    depends_on:
      - user-service
      - auth-service
      - notification-service

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./services/user-service:/app
    networks:
      - taeheonai-network

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./services/auth-service:/app
    networks:
      - taeheonai-network

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./services/notification-service:/app
    networks:
      - taeheonai-network

networks:
  taeheonai-network:
    driver: bridge 